### PR TITLE
Fix macOS bugs

### PR DESCRIPTION
**Pull request by unellma**

### CODE REVIEW

**Comment by hero09016** [comment]
I tested this app and there is no bug.

**Review by kcvijay — COMMENTED** [review]
There is NO bug now in MacOS.

**Comment by unellma** [comment]
> There is NO bug now in MacOS.

Can you please approve it if you don't see any bugs?

**Review by appketo — APPROVED** [review]
- Pulled changes
- Tested in macOS
- Opened browser from dock several times, 3-5
- I cannot reproduce the bugs, however I see console errors
- Fix in another task/ticket those console errors
- I like the changes and would approve it

**Review by kcvijay — APPROVED** [review]
approved changes.

**Pull request merged**
