### PR TITLE
UP-32 add right-click to Save Image As

### PR DESCRIPTION
**Pull request by Jessemwangi**

### CODE REVIEW

**Review by unellma — COMMENTED** [review]
It is not working... when clicked on "Save Image As...", throws following exception

```
(node:82329) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'session')
    at /Users/anderson/throwaway/unelma-browser/.webpack/main/index.js:29633:40
    at new Promise (<anonymous>)
    at module.exports.download (/Users/anderson/throwaway/unelma-browser/.webpack/main/index.js:29629:54)
    at click (/Users/anderson/throwaway/unelma-browser/.webpack/main/index.js:29154:11)
    at MenuItem.click (node:electron/js2c/browser_init:73:1908)
    at a._executeCommand (node:electron/js2c/browser_init:81:2453)
```

It should in practice open a dialog box and let user save it in local computer

**Comment by Jessemwangi** [comment]
> It is not working... when clicked on "Save Image As...", throws following exception
> 
> ```
> (node:82329) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'session')
>     at /Users/anderson/throwaway/unelma-browser/.webpack/main/index.js:29633:40
>     at new Promise (<anonymous>)
>     at module.exports.download (/Users/anderson/throwaway/unelma-browser/.webpack/main/index.js:29629:54)
>     at click (/Users/anderson/throwaway/unelma-browser/.webpack/main/index.js:29154:11)
>     at MenuItem.click (node:electron/js2c/browser_init:73:1908)
>     at a._executeCommand (node:electron/js2c/browser_init:81:2453)
> ```
> 
> It should in practice open a dialog box and let user save it in local computer

Dialog pop up has been enabled

**Review by unellma — COMMENTED** [review]
Does not work as intended (opens the dialog box but does not save the file locally in user's computer) 

Perhaps you can try something like this:

•  The dialog.showSaveDialog function takes a second argument, which is a callback function that receives the file path chosen by the user. You need to pass this callback function and use it to save the image to the file path. You can use the fs module to write the image data to the file. You can also use the parameters.srcURL property to get the URL of the image that was right-clicked.

•  The defaultPath option in the dialog options should be a string, not an expression. You can use the path module to join the user's home directory with a default file name, such as 'image.png'. You can also use the parameters.title property to get the title of the image and use it as part of the file name.

•  The prepend function should return an array of menu items, not just one. You can use the spread operator (...) to concatenate your custom menu item with the defaultActions array.

Here is one possible way to rewrite your code to fix these issues

```
const { dialog } = require("electron");
const fs = require("fs");
const path = require("path");

prepend: (defaultActions, parameters, browserWindow) => [
{
label: 'Save Image As ...',
visible: parameters.mediaType === 'image',
click: () => {
dialog.showSaveDialog(browserWindow, {
title: 'Save As',
defaultPath: path.join(process.env.HOME, ${parameters.title || 'image'}.png)
}, (filePath) => {
if (filePath) {
// download and save the image
const request = require('request');
request.get(parameters.srcURL, {encoding: 'binary'}, (error, response, body) => {
if (!error && response.statusCode === 200) {
fs.writeFile(filePath, body, 'binary', (err) => {
if (err) {
console.error(err);
}
});
}
});
}
});
}
},
...defaultActions
]
```

**Comment by unellma** [comment]
- Pulled the changes
- Seems it is working (only drawback is user have to insert file extension at the end of file name e.g. png, jpeg, jpg )
- If user does not insert file extension image is not rendered
- I will accept it as it is now and I hope this could be improved in future

**Review by unellma — APPROVED** [review]

**Review by amitkalwar — APPROVED** [review]
it's working from my side

**Pull request merged**
